[package]
name = "udisks-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = { version = "3.15.0", features = ["tokio"] }
#example and testing
tokio = { version = "1.36.0", features = ["full"] }

[dev-dependecies]
