// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../..
// from ../../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) UDISKS_ERROR_ALREADY_CANCELLED);
    PRINT_CONSTANT((gint) UDISKS_ERROR_ALREADY_MOUNTED);
    PRINT_CONSTANT((gint) UDISKS_ERROR_ALREADY_UNMOUNTING);
    PRINT_CONSTANT((gint) UDISKS_ERROR_CANCELLED);
    PRINT_CONSTANT((gint) UDISKS_ERROR_DEVICE_BUSY);
    PRINT_CONSTANT((gint) UDISKS_ERROR_FAILED);
    PRINT_CONSTANT((gint) UDISKS_ERROR_ISCSI_DAEMON_TRANSPORT_FAILED);
    PRINT_CONSTANT((gint) UDISKS_ERROR_ISCSI_HOST_NOT_FOUND);
    PRINT_CONSTANT((gint) UDISKS_ERROR_ISCSI_IDMB);
    PRINT_CONSTANT((gint) UDISKS_ERROR_ISCSI_LOGIN_AUTH_FAILED);
    PRINT_CONSTANT((gint) UDISKS_ERROR_ISCSI_LOGIN_FAILED);
    PRINT_CONSTANT((gint) UDISKS_ERROR_ISCSI_LOGIN_FATAL);
    PRINT_CONSTANT((gint) UDISKS_ERROR_ISCSI_LOGOUT_FAILED);
    PRINT_CONSTANT((gint) UDISKS_ERROR_ISCSI_NOT_CONNECTED);
    PRINT_CONSTANT((gint) UDISKS_ERROR_ISCSI_NO_FIRMWARE);
    PRINT_CONSTANT((gint) UDISKS_ERROR_ISCSI_NO_OBJECTS_FOUND);
    PRINT_CONSTANT((gint) UDISKS_ERROR_ISCSI_TRANSPORT_FAILED);
    PRINT_CONSTANT((gint) UDISKS_ERROR_ISCSI_UNKNOWN_DISCOVERY_TYPE);
    PRINT_CONSTANT((gint) UDISKS_ERROR_MOUNTED_BY_OTHER_USER);
    PRINT_CONSTANT((gint) UDISKS_ERROR_NOT_AUTHORIZED);
    PRINT_CONSTANT((gint) UDISKS_ERROR_NOT_AUTHORIZED_CAN_OBTAIN);
    PRINT_CONSTANT((gint) UDISKS_ERROR_NOT_AUTHORIZED_DISMISSED);
    PRINT_CONSTANT((gint) UDISKS_ERROR_NOT_MOUNTED);
    PRINT_CONSTANT((gint) UDISKS_ERROR_NOT_SUPPORTED);
    PRINT_CONSTANT(UDISKS_ERROR_NUM_ENTRIES);
    PRINT_CONSTANT((gint) UDISKS_ERROR_OPTION_NOT_PERMITTED);
    PRINT_CONSTANT((gint) UDISKS_ERROR_TIMED_OUT);
    PRINT_CONSTANT((gint) UDISKS_ERROR_WOULD_WAKEUP);
    PRINT_CONSTANT(UDISKS_MAJOR_VERSION);
    PRINT_CONSTANT(UDISKS_MICRO_VERSION);
    PRINT_CONSTANT(UDISKS_MINOR_VERSION);
    PRINT_CONSTANT((guint) UDISKS_PARTITION_TYPE_INFO_FLAGS_CREATE_ONLY);
    PRINT_CONSTANT((guint) UDISKS_PARTITION_TYPE_INFO_FLAGS_HIDDEN);
    PRINT_CONSTANT((guint) UDISKS_PARTITION_TYPE_INFO_FLAGS_NONE);
    PRINT_CONSTANT((guint) UDISKS_PARTITION_TYPE_INFO_FLAGS_RAID);
    PRINT_CONSTANT((guint) UDISKS_PARTITION_TYPE_INFO_FLAGS_SWAP);
    PRINT_CONSTANT((guint) UDISKS_PARTITION_TYPE_INFO_FLAGS_SYSTEM);
    return 0;
}
