// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{Block};
use glib::{translate::*};

glib::wrapper! {
    #[doc(alias = "UDisksBlockSkeleton")]
    pub struct BlockSkeleton(Object<ffi::UDisksBlockSkeleton, ffi::UDisksBlockSkeletonClass>) @implements Block;

    match fn {
        type_ => || ffi::udisks_block_skeleton_get_type(),
    }
}

impl BlockSkeleton {
        pub const NONE: Option<&'static BlockSkeleton> = None;
    

    #[doc(alias = "udisks_block_skeleton_new")]
    pub fn new() -> BlockSkeleton {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::udisks_block_skeleton_new())
        }
    }
}

impl Default for BlockSkeleton {
                     fn default() -> Self {
                         Self::new()
                     }
                 }
