// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{DriveAta};
use glib::{translate::*};

glib::wrapper! {
    #[doc(alias = "UDisksDriveAtaSkeleton")]
    pub struct DriveAtaSkeleton(Object<ffi::UDisksDriveAtaSkeleton, ffi::UDisksDriveAtaSkeletonClass>) @implements DriveAta;

    match fn {
        type_ => || ffi::udisks_drive_ata_skeleton_get_type(),
    }
}

impl DriveAtaSkeleton {
        pub const NONE: Option<&'static DriveAtaSkeleton> = None;
    

    #[doc(alias = "udisks_drive_ata_skeleton_new")]
    pub fn new() -> DriveAtaSkeleton {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::udisks_drive_ata_skeleton_new())
        }
    }
}

impl Default for DriveAtaSkeleton {
                     fn default() -> Self {
                         Self::new()
                     }
                 }
