// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{Encrypted};
use glib::{translate::*};

glib::wrapper! {
    #[doc(alias = "UDisksEncryptedSkeleton")]
    pub struct EncryptedSkeleton(Object<ffi::UDisksEncryptedSkeleton, ffi::UDisksEncryptedSkeletonClass>) @implements Encrypted;

    match fn {
        type_ => || ffi::udisks_encrypted_skeleton_get_type(),
    }
}

impl EncryptedSkeleton {
        pub const NONE: Option<&'static EncryptedSkeleton> = None;
    

    #[doc(alias = "udisks_encrypted_skeleton_new")]
    pub fn new() -> EncryptedSkeleton {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::udisks_encrypted_skeleton_new())
        }
    }
}

impl Default for EncryptedSkeleton {
                     fn default() -> Self {
                         Self::new()
                     }
                 }
