// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{Filesystem};
use glib::{translate::*};

glib::wrapper! {
    #[doc(alias = "UDisksFilesystemSkeleton")]
    pub struct FilesystemSkeleton(Object<ffi::UDisksFilesystemSkeleton, ffi::UDisksFilesystemSkeletonClass>) @implements Filesystem;

    match fn {
        type_ => || ffi::udisks_filesystem_skeleton_get_type(),
    }
}

impl FilesystemSkeleton {
        pub const NONE: Option<&'static FilesystemSkeleton> = None;
    

    #[doc(alias = "udisks_filesystem_skeleton_new")]
    pub fn new() -> FilesystemSkeleton {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::udisks_filesystem_skeleton_new())
        }
    }
}

impl Default for FilesystemSkeleton {
                     fn default() -> Self {
                         Self::new()
                     }
                 }
