// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{Job};
use glib::{translate::*};

glib::wrapper! {
    #[doc(alias = "UDisksJobSkeleton")]
    pub struct JobSkeleton(Object<ffi::UDisksJobSkeleton, ffi::UDisksJobSkeletonClass>) @implements Job;

    match fn {
        type_ => || ffi::udisks_job_skeleton_get_type(),
    }
}

impl JobSkeleton {
        pub const NONE: Option<&'static JobSkeleton> = None;
    

    #[doc(alias = "udisks_job_skeleton_new")]
    pub fn new() -> JobSkeleton {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::udisks_job_skeleton_new())
        }
    }
}

impl Default for JobSkeleton {
                     fn default() -> Self {
                         Self::new()
                     }
                 }
