// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{LogicalVolume};
use glib::{translate::*};

glib::wrapper! {
    #[doc(alias = "UDisksLogicalVolumeSkeleton")]
    pub struct LogicalVolumeSkeleton(Object<ffi::UDisksLogicalVolumeSkeleton, ffi::UDisksLogicalVolumeSkeletonClass>) @implements LogicalVolume;

    match fn {
        type_ => || ffi::udisks_logical_volume_skeleton_get_type(),
    }
}

impl LogicalVolumeSkeleton {
        pub const NONE: Option<&'static LogicalVolumeSkeleton> = None;
    

    #[doc(alias = "udisks_logical_volume_skeleton_new")]
    pub fn new() -> LogicalVolumeSkeleton {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::udisks_logical_volume_skeleton_new())
        }
    }
}

impl Default for LogicalVolumeSkeleton {
                     fn default() -> Self {
                         Self::new()
                     }
                 }
