// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ManagerLVM2};
use glib::{translate::*};

glib::wrapper! {
    #[doc(alias = "UDisksManagerLVM2Skeleton")]
    pub struct ManagerLVM2Skeleton(Object<ffi::UDisksManagerLVM2Skeleton, ffi::UDisksManagerLVM2SkeletonClass>) @implements ManagerLVM2;

    match fn {
        type_ => || ffi::udisks_manager_lvm2_skeleton_get_type(),
    }
}

impl ManagerLVM2Skeleton {
        pub const NONE: Option<&'static ManagerLVM2Skeleton> = None;
    

    #[doc(alias = "udisks_manager_lvm2_skeleton_new")]
    pub fn new() -> ManagerLVM2Skeleton {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::udisks_manager_lvm2_skeleton_new())
        }
    }
}

impl Default for ManagerLVM2Skeleton {
                     fn default() -> Self {
                         Self::new()
                     }
                 }
