// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT


glib::wrapper! {
    #[doc(alias = "UDisksObjectProxy")]
    pub struct ObjectProxy(Object<ffi::UDisksObjectProxy, ffi::UDisksObjectProxyClass>);

    match fn {
        type_ => || ffi::udisks_object_proxy_get_type(),
    }
}

impl ObjectProxy {
        pub const NONE: Option<&'static ObjectProxy> = None;
    

    //#[doc(alias = "udisks_object_proxy_new")]
    //pub fn new(connection: /*Ignored*/&gio::DBusConnection, object_path: &str) -> ObjectProxy {
    //    unsafe { TODO: call ffi:udisks_object_proxy_new() }
    //}
}
