// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use glib::{translate::*};

glib::wrapper! {
    #[doc(alias = "UDisksObjectInfo")]
    pub struct ObjectInfo(Object<ffi::UDisksObjectInfo>);

    match fn {
        type_ => || ffi::udisks_object_info_get_type(),
    }
}

impl ObjectInfo {
    #[doc(alias = "udisks_object_info_get_description")]
    #[doc(alias = "get_description")]
    pub fn description(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::udisks_object_info_get_description(self.to_glib_none().0))
        }
    }

    //#[doc(alias = "udisks_object_info_get_icon")]
    //#[doc(alias = "get_icon")]
    //pub fn icon(&self) -> /*Ignored*/Option<gio::Icon> {
    //    unsafe { TODO: call ffi:udisks_object_info_get_icon() }
    //}

    //#[doc(alias = "udisks_object_info_get_icon_symbolic")]
    //#[doc(alias = "get_icon_symbolic")]
    //pub fn icon_symbolic(&self) -> /*Ignored*/Option<gio::Icon> {
    //    unsafe { TODO: call ffi:udisks_object_info_get_icon_symbolic() }
    //}

    #[doc(alias = "udisks_object_info_get_media_description")]
    #[doc(alias = "get_media_description")]
    pub fn media_description(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::udisks_object_info_get_media_description(self.to_glib_none().0))
        }
    }

    //#[doc(alias = "udisks_object_info_get_media_icon")]
    //#[doc(alias = "get_media_icon")]
    //pub fn media_icon(&self) -> /*Ignored*/Option<gio::Icon> {
    //    unsafe { TODO: call ffi:udisks_object_info_get_media_icon() }
    //}

    //#[doc(alias = "udisks_object_info_get_media_icon_symbolic")]
    //#[doc(alias = "get_media_icon_symbolic")]
    //pub fn media_icon_symbolic(&self) -> /*Ignored*/Option<gio::Icon> {
    //    unsafe { TODO: call ffi:udisks_object_info_get_media_icon_symbolic() }
    //}

    #[doc(alias = "udisks_object_info_get_name")]
    #[doc(alias = "get_name")]
    pub fn name(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::udisks_object_info_get_name(self.to_glib_none().0))
        }
    }

    //#[doc(alias = "udisks_object_info_get_object")]
    //#[doc(alias = "get_object")]
    //pub fn object(&self) -> /*Ignored*/Option<Object> {
    //    unsafe { TODO: call ffi:udisks_object_info_get_object() }
    //}

    #[doc(alias = "udisks_object_info_get_one_liner")]
    #[doc(alias = "get_one_liner")]
    pub fn one_liner(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::udisks_object_info_get_one_liner(self.to_glib_none().0))
        }
    }

    #[doc(alias = "udisks_object_info_get_sort_key")]
    #[doc(alias = "get_sort_key")]
    pub fn sort_key(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::udisks_object_info_get_sort_key(self.to_glib_none().0))
        }
    }
}
