// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{Partition};
use glib::{translate::*};

glib::wrapper! {
    #[doc(alias = "UDisksPartitionSkeleton")]
    pub struct PartitionSkeleton(Object<ffi::UDisksPartitionSkeleton, ffi::UDisksPartitionSkeletonClass>) @implements Partition;

    match fn {
        type_ => || ffi::udisks_partition_skeleton_get_type(),
    }
}

impl PartitionSkeleton {
        pub const NONE: Option<&'static PartitionSkeleton> = None;
    

    #[doc(alias = "udisks_partition_skeleton_new")]
    pub fn new() -> PartitionSkeleton {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::udisks_partition_skeleton_new())
        }
    }
}

impl Default for PartitionSkeleton {
                     fn default() -> Self {
                         Self::new()
                     }
                 }
