// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{PhysicalVolume};
use glib::{translate::*};

glib::wrapper! {
    #[doc(alias = "UDisksPhysicalVolumeSkeleton")]
    pub struct PhysicalVolumeSkeleton(Object<ffi::UDisksPhysicalVolumeSkeleton, ffi::UDisksPhysicalVolumeSkeletonClass>) @implements PhysicalVolume;

    match fn {
        type_ => || ffi::udisks_physical_volume_skeleton_get_type(),
    }
}

impl PhysicalVolumeSkeleton {
        pub const NONE: Option<&'static PhysicalVolumeSkeleton> = None;
    

    #[doc(alias = "udisks_physical_volume_skeleton_new")]
    pub fn new() -> PhysicalVolumeSkeleton {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::udisks_physical_volume_skeleton_new())
        }
    }
}

impl Default for PhysicalVolumeSkeleton {
                     fn default() -> Self {
                         Self::new()
                     }
                 }
