// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{VDOVolume};
use glib::{translate::*};

glib::wrapper! {
    #[doc(alias = "UDisksVDOVolumeSkeleton")]
    pub struct VDOVolumeSkeleton(Object<ffi::UDisksVDOVolumeSkeleton, ffi::UDisksVDOVolumeSkeletonClass>) @implements VDOVolume;

    match fn {
        type_ => || ffi::udisks_vdo_volume_skeleton_get_type(),
    }
}

impl VDOVolumeSkeleton {
        pub const NONE: Option<&'static VDOVolumeSkeleton> = None;
    

    #[doc(alias = "udisks_vdo_volume_skeleton_new")]
    pub fn new() -> VDOVolumeSkeleton {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::udisks_vdo_volume_skeleton_new())
        }
    }
}

#[cfg(feature = "v2_9")]
#[cfg_attr(docsrs, doc(cfg(feature = "v2_9")))]
impl Default for VDOVolumeSkeleton {
                     fn default() -> Self {
                         Self::new()
                     }
                 }
