// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{VolumeGroup};
use glib::{translate::*};

glib::wrapper! {
    #[doc(alias = "UDisksVolumeGroupSkeleton")]
    pub struct VolumeGroupSkeleton(Object<ffi::UDisksVolumeGroupSkeleton, ffi::UDisksVolumeGroupSkeletonClass>) @implements VolumeGroup;

    match fn {
        type_ => || ffi::udisks_volume_group_skeleton_get_type(),
    }
}

impl VolumeGroupSkeleton {
        pub const NONE: Option<&'static VolumeGroupSkeleton> = None;
    

    #[doc(alias = "udisks_volume_group_skeleton_new")]
    pub fn new() -> VolumeGroupSkeleton {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::udisks_volume_group_skeleton_new())
        }
    }
}

impl Default for VolumeGroupSkeleton {
                     fn default() -> Self {
                         Self::new()
                     }
                 }
