[options]
library = "UDisks"
version = "2.0"
min_cfg_version = "2.0"
target_path = "."
girs_directories = ["../gir-files", "../"]
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

generate = [
    "UDisks.BlockLVM2",
    "UDisks.BlockLVM2Proxy",
    "UDisks.BlockLVM2Skeleton",
    "UDisks.BlockProxy",
    "UDisks.BlockSkeleton",
    "UDisks.DriveAta",
    "UDisks.DriveAtaProxy",
    "UDisks.DriveAtaSkeleton",
    "UDisks.DriveProxy",
    "UDisks.DriveSkeleton",
    "UDisks.Encrypted",
    "UDisks.EncryptedProxy",
    "UDisks.EncryptedSkeleton",
    "UDisks.Error",
    "UDisks.FilesystemBTRFS",
    "UDisks.FilesystemBTRFSProxy",
    "UDisks.FilesystemBTRFSSkeleton",
    "UDisks.FilesystemProxy",
    "UDisks.FilesystemSkeleton",
    "UDisks.JobProxy",
    "UDisks.JobSkeleton",
    "UDisks.LogicalVolume",
    "UDisks.LogicalVolumeProxy",
    "UDisks.LogicalVolumeSkeleton",
    "UDisks.Loop",
    "UDisks.LoopProxy",
    "UDisks.LoopSkeleton",
    "UDisks.ManagerBTRFS",
    "UDisks.ManagerBTRFSProxy",
    "UDisks.ManagerBTRFSSkeleton",
    "UDisks.ManagerLVM2",
    "UDisks.ManagerLVM2Proxy",
    "UDisks.ManagerLVM2Skeleton",
    "UDisks.ManagerProxy",
    "UDisks.ManagerSkeleton",
    "UDisks.MDRaid",
    "UDisks.MDRaidProxy",
    "UDisks.MDRaidSkeleton",
    # "UDisks.Object",
    "UDisks.ObjectInfo",
    "UDisks.ObjectManagerClient",
    "UDisks.ObjectProxy",
    "UDisks.ObjectSkeleton",
    "UDisks.Partition",
    "UDisks.PartitionInfo",
    "UDisks.PartitionProxy",
    "UDisks.PartitionSkeleton",
    "UDisks.PartitionTableProxy",
    "UDisks.PartitionTableSkeleton",
    "UDisks.PartitionTypeInfo",
    "UDisks.PartitionTypeInfoFlags",
    "UDisks.PhysicalVolume",
    "UDisks.PhysicalVolumeProxy",
    "UDisks.PhysicalVolumeSkeleton",
    "UDisks.Swapspace",
    "UDisks.SwapspaceProxy",
    "UDisks.SwapspaceSkeleton",
    "UDisks.VDOVolume",
    "UDisks.VDOVolumeProxy",
    "UDisks.VDOVolumeSkeleton",
    "UDisks.VolumeGroup",
    "UDisks.VolumeGroupProxy",
    "UDisks.VolumeGroupSkeleton",
]

[[object]]
name = "UDisks.Block"
status = "generate"
    [[object.function]]
    name = "set_symlinks"
    ignore = true
    [[object.function]]
    name = "set_userspace_mount_options"
    ignore = true

[[object]]
name = "UDisks.Client"
status = "generate"
    [[object.function]]
    name = "get_media_compat_for_display"
    ignore = true

[[object]]
name = "UDisks.Drive"
status = "generate"
    [[object.function]]
    name = "set_media_compatibility"
    ignore = true

[[object]]
name = "UDisks.Filesystem"
status = "generate"
    [[object.function]]
    name = "set_mount_points"
    ignore = true


[[object]]
name = "UDisks.Job"
status = "generate"
    [[object.function]]
    name = "set_objects"
    ignore = true


[[object]]
name = "UDisks.Manager"
status = "generate"
    [[object.function]]
    name = "set_supported_filesystems"
    ignore = true
    [[object.function]]
    name = "set_supported_encryption_types"
    ignore = true


[[object]]
name = "UDisks.PartitionTable"
status = "generate"
    [[object.function]]
    name = "set_partitions"
    ignore = true



manual = [
    "Gio.AsyncReadyCallback",
    "Gio.AsyncResult",
    "Gio.BusType",
    "Gio.Cancellable",
    "Gio.DBusConnection",
    # "Gio.DBusInterfaceInfo",
    "Gio.DBusMethodInvocation",
    "Gio.DBusObject",
    # "Gio.DBusObjectManager",
    # "Gio.DBusObjectManagerClient",
    # "Gio.DBusObjectManagerClientFlags",
    "Gio.DBusProxyFlags",
    "Gio.Icon",
    "Gio.UnixFDList",
    "GLib.Error",
    # "GLib.ObjectClass",
    "GLib.Variant",
    # "GObject.ObjectClass",
]
